### ISSUE TITLE
Remove "for OsmAnd" from project description

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#15]
This project is now more than just for OsmAnd :-)

Current description is: "Parse listing from Wikivoyage to create data files for OsmAnd"

How about: "Data extracted from Wikivoyage, the free travel guide at http://wikivoyage.org. Leverage Wikivoyage listings on your smartphone, or in your own mashups."

**Comment by baturin** [comment]
Changed.
