### ISSUE TITLE
Generic XML output, with all parameters

### ISSUE THREAD

**Issue by Freundschaft** [baturin/wikivoyage-listings#16]
Some POIs have links to the websites of the venue associated with their title, but the website link is omitted in the XML, would it be possible to change that in the conversion tool?

Cheers & Thanks!

**Comment by nicolas-raoul** [comment]
If it is not that's a bug, thanks for letting us know!

**Comment by nicolas-raoul** [comment]
What is the URL of the XML file you are talking about?

**Comment by Freundschaft** [comment]
http://wvpoi.batalex.ru/download/listings/wikivoyage-listings-en-latest.xml
I couldnt see them there, also in the code I dont see URL output: https://github.com/baturin/wikivoyage-listings/blob/master/src/main/java/org/wikivoyage/listings/output/OsmXml.java
Is URL supposed to be in OsmXML?

**Comment by nicolas-raoul** [comment]
Looking more closely, I remember that we only have special-purpose XML formats.

If you want a general-purpose XML containing all parameters, please create it by taking https://github.com/baturin/wikivoyage-listings/tree/master/src/main/java/org/wikivoyage/listings/output as a model and send it to us, Cheers!

**Comment by nicolas-raoul** [comment]
OsmXML only contains the fields useful in OsmAnd (I think), so no POI websites.

You should create a new XML output type, or use a more complete output like CSV.

**Comment by Freundschaft** [comment]
alright, will create a pull request later on, if I write a new output, will you use this as for generation for your listings website? thanks!

**Comment by nicolas-raoul** [comment]
The website is managed by @baturin so the decision is his, but I guess he will accept, if you write the code :-)
Generic XML would be useful as it is more robust than CSV, even if processing can be slower.

**Comment by Freundschaft** [comment]
@patrickwieth has made changes for a PR:
https://github.com/baturin/wikivoyage-listings/pull/24

is this mergeable?

Cheers
