### ISSUE TITLE
Parse diplomatic representations (embassies and consulates)

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#23]
They are listed like this in the English Wikipedia:

```
* {{flag|Afghanistan}} {{listing
| name=Afghanistan | url=http://embassyofafghanistan.org/ | email=
| address=2341 Wyoming Ave NW | lat= | long= | directions=
| phone=+1 202 234-3770 | tollfree= | fax=
| hours= | price=
| content=
}}
```

It would be a new type of listing, called maybe "diplomatic-representation".

**Comment by imanc** [comment]
I'll study this.

**Comment by nicolas-raoul** [comment]
@imanc Example of an article with many diplomatic representations: https://en.wikivoyage.org/wiki/Karachi#Consulates
I suggest looking for {{flag}} in each article, and using it to give a type to the listing that follows immediately.

**Comment by nicolas-raoul** [comment]
Tested, it works, thanks a lot @imanc ! Merged.

**Comment by nicolas-raoul** [comment]
@imanc Here is the following mission, if you still have time :-) : #43

**Comment by imanc** [comment]
I'm sorry but I'm very busy at the moment

**Comment by nicolas-raoul** [comment]
@imanc OK no problem, have a great day :-)
