### ISSUE TITLE
Only use complete dumps

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#25]
The folder on the server is created before all files are ready. Until ready it is called a "Partial dump".

![screenshot from 2016-08-01 17-59-11](https://cloud.githubusercontent.com/assets/99590/17288813/d146a3c0-5811-11e6-977e-531ee10dea37.png)

This makes the tool fail if we are unlucky enough to run at the wrong time.

**Comment by imanc** [comment]
Hi, I'm trying to fix this bug. If a Partial dump is found what should the program do, try with the latest complete dump?

**Comment by nicolas-raoul** [comment]
Yes, exactly :-)

Sorry for not posting the HTML, I guess you can find it by looking for dumps that are being created right now.

**Comment by imanc** [comment]
Another question :-)
What's the best method to check if the dump is partial: parse the html to find "Partial Dump" text or to check the json status file associated with the dump?
https://dumps.wikimedia.org/enwikivoyage/20170801/dumpstatus.json at key "status"

`{
"version": "0.8",
"jobs": {
"articlesmultistreamdump": {
"status": "done",
"files": {
"enwikivoyage-20170801-pages-articles-multistream.xml.bz2" ...`

**Comment by nicolas-raoul** [comment]
Checking the HTML would probably work, but checking the JSON is worth bonus
points 🙂

**Comment by imanc** [comment]
I forked the repo and implemented a solution. It's my first contribution, I hope to have done it correctly.

**Comment by nicolas-raoul** [comment]
Great! After you have tested your solution, please send a pull request :-)

**Comment by nicolas-raoul** [comment]
Thanks @imanc !
If you are up for another one, how about #23? It would be very useful :-)

**Comment by imanc** [comment]
Hi, I'm happy that my work was useful. I'll check #23 but in another post you mentioned also #34. Which one has priority?

**Comment by nicolas-raoul** [comment]
Actually I forgot I had implemented #34 already, so I suggest #23 :-)
