### ISSUE TITLE
wvpoi.batalex.ru downloads out-of-date

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#27]
Are you too busy to maintain the server maybe?
Wikivoyage is now getting a now of Wikidata identifier, so the data is getting more and more interesting for people :-)
Cheers!

**Comment by baturin** [comment]
Hi Nicolas,
I've finally managed to find time, resolve new code/server issues and update data. 
Please check!

**Comment by nicolas-raoul** [comment]
Wonderful, thanks :-)
