### ISSUE TITLE
Export to KML

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#29]
GPX is not supported by Maps.me, Google Earth and other apps

**Comment by baturin** [comment]
We already have KML files, for example:
http://wvpoi.batalex.ru/download/listings/wikivoyage-listings-fr-latest.kml

**Comment by nicolas-raoul** [comment]
Sorry I don't know how I forgot it!
https://github.com/baturin/wikivoyage-listings/blob/master/src/main/java/org/wikivoyage/listings/output/KML.java
