### ISSUE TITLE
Create a new OutputFormat that generates a validation report

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#3]
The generated output would be a report that points out errors found in the WIkivoyagePOI objects, for instance malformed coordinates etc.

Ideally the report would include HTTP links to directly go fix the data on Wikivoyage, see an example at https://en.wikivoyage.org/wiki/User:Syced/Syntax_checks

**Comment by nicolas-raoul** [comment]
https://commons.apache.org/proper/commons-validator/ can be used to validate URLs and email addresses.

Alexey, if the report is created as HTML, would you accept to host it on your server?

**Comment by baturin** [comment]
No problem, I think HTML would be preferred - we will be able to see fresh reports directly from the site.

**Comment by nicolas-raoul** [comment]
The report results should be grouped by article (for efficient edition), and the articles should be either:

- Organized on a map, so that people can process errors in places they are familiar with.
- Randomized, so that people don't always process the same articles, and to prevent potential false-positives from making up most of the beginning of the list.
