### ISSUE TITLE
Check the validity of the Wikidata attribute

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#30]
Check whether the Wikidata item actually exists.
This probably means performing a request per item, which is time-consuming, so it should be disabled by default.

**Comment by zstojanovic** [comment]
I would like to take stab at this.

I was thinking along the lines of:
- add an new command line parameter that turns on additional check
- additional check would be performed in WikidataValidator
- the check would use an API call ie. https://www.wikidata.org/w/api.php?action=wbgetentities&props=info&ids=Q42455342&format=json

I would like to hear if this solution would be appropriate or are there better approaches.

**Comment by nicolas-raoul** [comment]
@zstojanovic OK, it's yours :-)
I am currently not aware of any better approach.

**Comment by nicolas-raoul** [comment]
I guess we want to avoid redirects. All QIDs should point to the real thing, not to an old items which is now only a redirect.
Here is how a redirect looks like: https://www.wikidata.org/w/api.php?action=wbgetentities&props=info&ids=Q39072913&format=json

**Comment by nicolas-raoul** [comment]
The SPARQL query at https://www.wikidata.org/wiki/Wikidata:Project_chat#How_to_efficiently_check_the_existence_of_many_Wikidata_items.3F sounds much more efficient, and it can distinguish redirects.

The | syntax suggested by Pasleim might be worth trying too.

If we can validate in batches of like 100, then I guess we might as well do the check by default, without needed an option.

**Comment by zstojanovic** [comment]
Those are excellent remarks, thanks. I am now looking into the | syntax and the SPARQL query approaches.

The former is limited to 50 ids, and I couldn't find the limit for the SPARQL, but its [query service](https://www.wikidata.org/wiki/Wikidata:SPARQL_query_service#Interfacing) uses GET request, and that will probably be [limited on the server side](https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request). I'll try it and get back to you.

If we want to validate in bulk, current Validator interface probably won't be appropriate. I would suggest creating a new BulkValidator interface, and its first implementation WikidataBulkValidator which would replace the current WikidataValidator.

**Comment by nicolas-raoul** [comment]
Sounds good! :-)

**Comment by zstojanovic** [comment]
I prepared a PR for this #48 
Let me know what you think.
