### ISSUE TITLE
up-for-grabs.net

### ISSUE THREAD

**Issue by imanc** [baturin/wikivoyage-listings#38]
Hi, I don't know if this is the correct place to write but I want to get involved in open source and I found this project on up-for-grabs.net. Any help needed?

**Comment by nicolas-raoul** [comment]
Hello Dario,

We don't have a mailing list, so I guess using Issues for general discussion is OK :-)

Yes, definitely, we need help, and the good thing with this project is that there are many small things to do. So, welcome to the team! ^_^

Please browse t[he issues](https://github.com/baturin/wikivoyage-listings/issues) and choose one you like. Those with the "up-for-grabs" tag are well-defined and the best way for a newcomer to get started.

Personally I would suggest #25

**Comment by imanc** [comment]
OK, I'll study the code.

**Comment by nicolas-raoul** [comment]
@imanc seeing your skills at work has convinced me that you are more than a beginner, so if you are still motivated I would recommend #34 which is more complex but also much more rewarding as it will allow the data to be used by a much wider audience :-)
