### ISSUE TITLE
Accept URLs with accented characters

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#39]
Example: http://www.visitbotosani.ro/ro/2014/04/biserica-armenească-adormirea-maicii-domnului-2/

Reported as malformed, but I believe it is actually a valid URL, at least it works fine in Chromium and Firefox.

More examples at http://wvpoi.batalex.ru/download/listings/wikivoyage-listings-en-latest.validation-report.html

**Comment by darrenyoung89** [comment]
I have created a pull request #45 related to this issue. 
I will be browsing some of the other open issues on this repository so please let me know if the procedure that I followed for submitting on this were fine - I'm not sure if there are particular contribution guidelines which I should follow.

**Comment by nicolas-raoul** [comment]
Yes, great, thanks a lot for fixing this, nice code and adding associated unit tests is a great initiative :-)
