### ISSUE TITLE
Wikidata property not found anymore on German Wikivoyage?

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#44]
The number of Wikidata items found in the German Wikivoyage used to be 277 in October 2016, now it is zero.
Maybe they changed the property name?

**Comment by zstojanovic** [comment]
I've checked and the property name really did change to "wikidata". After changing it in code, I'm getting 1296 Wikidata items for German Wikivoyage.

I prepared a (pretty trivial) pull request #47 for this. Let me know if this is useful or not.
