### ISSUE TITLE
Remove invalid Wikidata identifier from output

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#49]
The CSV/SQL/etc files should not contain invalid QIDs.

Redirects might be thought as tolerable, but better remove them too, I would say, as there are not many and they might break some weakly-built tools.

**Comment by zstojanovic** [comment]
Can you explain the desired behavior in more detail?

If I'm not mistaken, current behavior is that when you use batch file generation (-daily-update option) the output files will not contain listings which are marked as invalid by **any validator**.

On the other hand, when you use single file generation (-generate option), output files will contain all the listings regardless of the validators.

Maybe you are talking about leaving all the listings, and just omitting the invalid QID?

Please clarify.

**Comment by nicolas-raoul** [comment]
I don't think the difference in behavior between -daily-update and -generate is on purpose, it sounds like I forgot to fix -generate.

In my opinion, all generated files should not contain any invalid data:
- If only coordinates are incorrect, then discard only the coordinates and keep the rest of the POI
- If only the QID is incorrect, then discard only the QID and keep the rest of the POI

Sorry to talk about this only now, as it may impact the architecture introduced by your last pull request :-/

**Comment by zstojanovic** [comment]
Ok, ok, I understand.
I'll see if I can come up with something and get back to you.

**Comment by zstojanovic** [comment]
OK, this took more time than I expected :)

Anyways, I tried a few different approaches, and the best I could come up with is in the PR (although still not 100% happy with it). Unfortunately it turned out to be a small rewrite of the validators, so additional and thorough testing is welcome.

Let me know what you think.
