### ISSUE TITLE
Invalid URL 'https://wayback.archive.org/web/20151121141021/http://www.iptv.org:80/iowastories/story.cfm/architecture/478/cia_20100407_50_buildings/video'

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#53]
I am not sure it is a great URL in terms of Wikivoyage content guidelines, but anyway it looks to me as a valid URL.

**Comment by nicolas-raoul** [comment]
The validating Java code must be modified to accept this kind of links.

**Comment by nicolas-raoul** [comment]
https://github.com/baturin/wikivoyage-listings/blob/master/src/main/java/org/wikivoyage/listings/validators/WebsiteURLValidator.java#L21
Maybe it is a problem of the upstream library, in which case please report a bug there and post a link to it here. Thanks! :-)

**Comment by kevin0x90** [comment]
#83 should also fix this issue.
