### ISSUE TITLE
Invalid URL 'http://art_en.incheon.go.kr/index.do'

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#54]
Should be valid

**Comment by infoalisaa** [comment]
Hello @nicolas-raoul!

 I am not sure if you were looking for the English language version of this website, but this is the English version I could validate: http://english.incheon.go.kr/index.do
 The original Korean version is this site: http://www.incheon.go.kr/index.do#btnGoLanguage
 Please let me know if you need me to update this link somewhere. I really would like to contribute!

Thanks!

**Comment by nicolas-raoul** [comment]
@infoalisaa Thanks for joining, and sorry for the late answer! :-)
One thing would be to fix the link at https://en.wikivoyage.org/wiki/Incheon#Do
But the main problem is that this URL should not have been considered invalid (I think), so modifying the Java code is necessary.

**Comment by infoalisaa** [comment]
@nicolas-raoul 

That’s okay! I was wondering if maybe my comment got lost somewhere. 
Can you let me know where in the Java code I need to go to to update this link?

Thanks!

**Comment by kevin0x90** [comment]
#83 should have also fixed this issue
