### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by Amantel** [baturin/wikivoyage-listings#55]
Hello!

I can see problems with encoding like `Sagrada Família` listed as `Sagrada Fam?lia` at http://wvpoi.batalex.ru/ latest. 
Here and at http://wvpoi.batalex.ru/ by date - everything is alright

**Comment by baturin** [comment]
Hello!
I've resolved another issue - the listings were not generated periodically for all languages except for English for quite a long time. I've launched listing generation and now the latest version of French/Russian/German listings seem to be correct, there are no encoding issues.
