### ISSUE TITLE
Modify getFlagElement() method

### ISSUE THREAD

**Issue by nsaiisasidhar** [baturin/wikivoyage-listings#67]
The Template for flag is named in respective local languages such as `Template: Bandera` in Spanish, `Template: Drapeaux` in French etc.. and so the `getFlagElement()` method needs to be changed accordingly.

Correct me if I'm wrong.

**Comment by nicolas-raoul** [comment]
Thanks for reporting this problem!
If you have time, we would very much welcome a pull request :-)
Thanks!
