### ISSUE TITLE
French wikivoyage input

### ISSUE THREAD

**Issue by nicolas-raoul** [baturin/wikivoyage-listings#8]
I am trying to add French wikivoyage input.
The syntax is quite different from Russian/English:

```
* {{Voir
| nom= | alt= | url= | email= | wikipédia= | wikidata= | facebook= 
| adresse= | latitude= | longitude= | direction= 
| image = 
| téléphone= | numéro gratuit= | téléphone portable= | fax= 
| prix= | horaire= 
| wifi= | handicap= | mise à jour=2015/11/16
| description=
}}
```

The listing types are:
```
aller
circuler
voir
faire
acheter
manger
sortir
se loger
ville
destination
représentation diplomatique
autres
```
I will try to match them to English types.

I can try to guess the language in some cases, but not when using `-input-file`... what do you suggest? Should we add a language command-line parameter?

**Comment by baturin** [comment]
I've added option "-input-lang" for explicit language specification when using dump file.
Still, it makes sense to detect language from dump itself - check "siteinfo/dbname" node:
<siteinfo>
  <sitename>Wikivoyage</sitename>
  <dbname>enwikivoyage</dbname>
...

**Comment by nicolas-raoul** [comment]
Oh good find thanks!
I guess this issue can be closed.
