### ISSUE TITLE
Error "Error: Could not find or load main class org.wikivoyage.listings.Main" (compile failure -tools.jar not found)

### ISSUE THREAD

**Issue by arnicas** [baturin/wikivoyage-listings#92]
Hi, I am not good with java... When I try to run wikivoyage-listings.sh, with or without args, I get the error 
"Error: Could not find or load main class org.wikivoyage.listings.Main"

perhaps I am having a path issue (java is findable tho)? or did I miss a step involving the data first?  I ran the gradlew command just fine.  I'm on ubuntu.

Lynn

**Comment by nicolas-raoul** [comment]
Hi Lynn,
What was the result of the `./gradlew jar` command? It sounds like it failed to compile.
Do you see a `wikivoyage-listings.jar` file?

**Comment by arnicas** [comment]
Hi Nicolas,
Huh, I thought it had run ok the first time but I guess not.  It says:

./gradlew jar --info
Starting Build
Settings evaluated using settings file '/master/settings.gradle'.
Projects loaded. Root project using build file '/home/jupyter/code/wikipedia/wikivoyage-listings/build.gradle'.
Included projects: [root project 'wikivoyage-listings']
Evaluating root project 'wikivoyage-listings' using build file '/home/jupyter/code/wikipedia/wikivoyage-listings/build.gradle'.
All projects evaluated.
Selected primary task 'jar' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar']
:compileJava (Thread[main,5,main]) started.
:compileJava
Executing task ':compileJava' (up-to-date check took 0.039 secs) due to:
  No history is available.
All input files are considered out-of-date for incremental task ':compileJava'.
Compiling with JDK Java compiler API.
:compileJava FAILED
:compileJava (Thread[main,5,main]) completed. Took 0.085 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

----
No wikivoyage-listings.jar at top level, in any case.  Is it supposed to build tools.jar first? 

Lynn

**Comment by nicolas-raoul** [comment]
Looks like this problem: https://stackoverflow.com/questions/11345193/gradle-does-not-find-tools-jar

**Comment by arnicas** [comment]
Woot, thank you so much.  I got the path set right to the JDK and it compiled this time.  I got the help to list out.

**Comment by nicolas-raoul** [comment]
Great to hear :-)
